
import java.awt.Component;
import java.awt.PopupMenu;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Obscu
 */
public class WindowFrame extends javax.swing.JFrame {
     ArrayList<JLabel> JlabelArray;
     ArrayList<JLabel> JlabelArray2;
     int y=0;
    /**
     * Creates new form WindowFrame
     */
    public WindowFrame() {
        
        JlabelArray = new ArrayList();
        initComponents();
        Gendatablock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneDatablockQueue = new javax.swing.JScrollPane();
        PanelDatablockQueue = new javax.swing.JPanel();
        PanelDatablock = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtDatablock = new javax.swing.JTextField();
        AddToQueue = new javax.swing.JButton();
        ScrollPanelVariable = new javax.swing.JScrollPane();
        PanelVariable = new javax.swing.JPanel();
        txtVariable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLC2Mobile Client");

        ScrollPaneDatablockQueue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 51, 255), new java.awt.Color(255, 0, 0), null, null));
        ScrollPaneDatablockQueue.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        ScrollPaneDatablockQueue.setToolTipText("");
        ScrollPaneDatablockQueue.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelDatablockQueue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 153), new java.awt.Color(51, 255, 153), null, null));
        PanelDatablockQueue.setMaximumSize(new java.awt.Dimension(300, 300));
        PanelDatablockQueue.setLayout(new java.awt.GridLayout(0, 1));
        ScrollPaneDatablockQueue.setViewportView(PanelDatablockQueue);

        PanelDatablock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 0, 255), new java.awt.Color(255, 0, 51), null, null));

        jLabel2.setText("Datablock Name:");

        TxtDatablock.setText("Hometest");

        AddToQueue.setText("Add to Queue");
        AddToQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToQueueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatablockLayout = new javax.swing.GroupLayout(PanelDatablock);
        PanelDatablock.setLayout(PanelDatablockLayout);
        PanelDatablockLayout.setHorizontalGroup(
            PanelDatablockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatablockLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtDatablock, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddToQueue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatablockLayout.setVerticalGroup(
            PanelDatablockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatablockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDatablockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDatablock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddToQueue))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelVariableLayout = new javax.swing.GroupLayout(PanelVariable);
        PanelVariable.setLayout(PanelVariableLayout);
        PanelVariableLayout.setHorizontalGroup(
            PanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVariableLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtVariable)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        PanelVariableLayout.setVerticalGroup(
            PanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVariable)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        ScrollPanelVariable.setViewportView(PanelVariable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneDatablockQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDatablock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPanelVariable))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneDatablockQueue)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDatablock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPanelVariable)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToQueueActionPerformed
        JlabelArray.get(y).setText(TxtDatablock.getText());
        y++;
    }//GEN-LAST:event_AddToQueueActionPerformed

    public void Gendatablock() {
       int i;
       for(i=0; i<=100; i++){
       JLabel jlabel = new JLabel(" ");
        JlabelArray.add(jlabel);
        PanelDatablockQueue.add((Component) JlabelArray.get(i));
        ScrollPaneDatablockQueue.setViewportView(PanelDatablockQueue); 
       }
}
      public void Gendatavariable() {
       int i;
       for(i=0; i<=5; i++){
       JLabel jlabel2 = new JLabel(" Um dois som ");
        JlabelArray2.add(jlabel2);
        PanelVariable.add((Component) JlabelArray2.get(i));
        ScrollPanelVariable.setViewportView(PanelVariable); 
        
       }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToQueue;
    private javax.swing.JPanel PanelDatablock;
    private javax.swing.JPanel PanelDatablockQueue;
    private javax.swing.JPanel PanelVariable;
    private javax.swing.JScrollPane ScrollPaneDatablockQueue;
    private javax.swing.JScrollPane ScrollPanelVariable;
    private javax.swing.JTextField TxtDatablock;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtVariable;
    // End of variables declaration//GEN-END:variables
}
